#!/bin/sh

xrdb -merge ~/.Xresources
xsetroot -cursor_name left_ptr
xset s off -dpms

# nitrogen --restore
# nm-applet &
# unclutter &
# picom &
alacritty &
# fcitx5 &
emacs &

if [ -f $HOME/.screenlayout/layout.sh ]; then
    $HOME/.screenlayout/layout.sh
fi

#exec $HOME/.xmonad/xmonad-x86_64-linux
exec dbus-launch leftwm
