#!/bin/sh

# xsetroot -cursor_name left_ptr
# xset s off -dpms
# nitrogen --restore
# 
# unclutter &
# picom &
# nm-applet --sm-disable &
# trayer --edge top --align right --SetDockType true --SetPartialStrut true \
#  --expand true --width 5 --transparent true --alpha 0 --tint 0x1e2127 --height 22 &

# alacritty &
# exec $HOME/.xmonad/xmonad-x86_64-linux
# exec i3
